cc_binary(
    name = "singleton_one",
    srcs = [
        "singleton_one.cc",
    ],
)

cc_binary(
    name = "singleton_two",
    srcs = [
        "singleton_two.cc",
    ],
)

cc_binary(
    name = "singleton_right",
    srcs = [
        "singleton_right.cc",
    ],
    deps = ["//base"],
)

cc_binary(
    name = "singleton",
    srcs = [
        "singleton.cc",
    ],
)

cc_binary(
    name = "singleton_copy_and_assign",
    srcs = [
        "singleton_copy_and_assign.cc",
    ],
)

cc_binary(
    name = "singleton_no_delete",
    srcs = [
        "singleton_no_delete.cc",
    ],
    deps = ["//base"],
)
