cc_binary(
    name = "singleton_one",
    srcs = [
        "singleton_one.cc",
    ],
)

cc_binary(
    name = "singleton_two",
    srcs = [
        "singleton_two.cc",
    ],
)

#cc_binary(
#    name = "singleton_right",
#    srcs = [
#        "singleton_right.cc",
#    ],
#)

cc_binary(
    name = "singleton",
    srcs = [
        "singleton.cc",
    ],
)
